baseline-data-form/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.static import serve 

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.default, name="default"),
    path("register/", views.register, name="register"),
    url(r'^favicon\.ico$', RedirectView.as_view(url=staticfiles_storage.url("favicons/favicon.ico"), permanent=True), name='favicon'),
    
    # URL for the main form
    path("<uuid:orgid>/", views.home, name="home"),

    # URL with info that the data was sent successfully 
    path("<uuid:orgid>/success/", views.success, name="success"),

    # URLs for files
    path("<uuid:orgid>/files/", views.files, name="files"),
    path("<uuid:orgid>/files/<uuid:fileid>/", views.delete_file, name="delete_file"),
    path(r'media/<path:path>', views.download_file, name="download_file"),
    
    # URLs for commands
    path("<uuid:orgid>/commands/", views.commands, name="commands"),
   
    # Feedback
    path("<uuid:orgid>/feedback/", views.feedback, name="feedback"),
    path("<uuid:orgid>/feedback/thanks/", views.feedback_thanks, name="feedback_thanks"),

    # URLs to get fields in plain text
    path("<uuid:orgid>/yamldata.yml", views.yaml_response, name="yaml_response"),
    path("<uuid:orgid>/yamldata.yml/", views.yaml_response, name="yaml_response"),
    
    path("<uuid:orgid>/commands.json", views.commands_response, name="commands_response"),
    path("<uuid:orgid>/commands.json/", views.commands_response, name="commands_response"),
]

main/forms.py
from django import forms
from .models import *
import yaml
from yaml.parser import ParserError, ScannerError
from .modules.commands_to_schema import *
import re

class OrganizationForm(forms.ModelForm):
    """A class used to generate form object from OrganizationModel object"""

    class Meta:
        model = OrganizationModel
        fields = ['company', 'yamldata', 'email_addresses',
                  'num_conf', 'comment_conf', 'commands']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['company'].widget.attrs['placeholder'] = "Solidex"
        self.fields['yamldata'].widget.attrs['placeholder'] = """Insert the data from your .yml file with valid syntax:
FG-100F:
  interfaces:
  - ip_mask: 0.0.0.0/0
    gw: 0.0.0.0
FM:
  interfaces:
  - ip_mask: 172.22.10.1/31
    gateway: 172.22.10.0
global:
  syslog: 0.0.0.0
  ntp: 0.0.0.0
  dns1: 0.0.0.0
        """
        self.fields['email_addresses'].widget.attrs['placeholder'] = "worker1@solidex.by, worker2@solidex.by"
        self.fields['comment_conf'].widget.attrs['placeholder'] = 'Example: Загрузите конфигурационные файлы всех устройств FortiGate'
        self.fields['commands'].widget.attrs['placeholder'] = """Provide required commands for each device in yaml syntax:
FG-100F:
  - show system interface
FM:
  - diag dvm device list
  - diag dvm adom list
        """
        not_required_fields = ['comment_conf', 'num_conf']
        for field in not_required_fields:
            self.fields[field].widget.attrs['required'] = False

        for x in self.fields:
            self.fields[x].widget.attrs['class'] = 'form-control'

    def clean_yamldata(self):
        """Validate that yamldata field is filled correctly"""
        yamldata = self.cleaned_data['yamldata']
        try:
            yaml.safe_load(yamldata)
        except (ScannerError, ParserError):
            raise forms.ValidationError('Parser error. Check yaml syntax\
                                        in "yamldata" field',
                                        code='invalid')
        return yamldata

    def clean_commands(self):
        """Validate that commands are provided correctly"""
        commands = self.cleaned_data['commands']
        if commands != '':
            try:
                data = yaml.safe_load(commands)
            # Check yaml syntax
            except (ScannerError, ParserError):
                raise forms.ValidationError('Parser error. Check yaml syntax\
                                            in "commands" field',
                                            code='invalid')
            try:
                convert_dict_array(data)
            # Check correctness of format
            except (TypeError, AttributeError):
                raise forms.ValidationError("Error. Specify commands in correct format",
                                            code='invalid')
        return commands

    def clean_email_addresses(self):
        """Validate that email addresses are provided in correct format"""
        addresses = self.cleaned_data['email_addresses']
        addr_list = addresses.split(", ")
        email_regex = "^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$"
        if not all(re.search(email_regex, addr) for addr in addr_list):
            raise forms.ValidationError('Wrong email format', code='invalid')
        return addresses


class DocumentForm(forms.ModelForm):
    """A class used to generate form object from DocumentModel object"""

    class Meta:
        model = DocumentModel
        fields = ['document', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['placeholder'] = 'Например: FortiGate config'

class FeedbackForm(forms.ModelForm):
    """A class used to represent feedback form"""

    class Meta:
        model = FeedbackModel
        fields = ['is_user_friendly', 'how_to_make_it_better']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for x in self.fields:
            self.fields[x].widget.attrs['class'] = 'form-control'

main/views.py
from django.shortcuts import render, get_object_or_404
from .forms import *
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views.generic.edit import FormView
from django.conf import settings
from django.core.mail import send_mail

import yaml, json
import os
from datetime import datetime

from .modules.commands_to_schema import *
from .modules.substitutions import *


def register(request):
    """
    Generate register page

    Path in URL: /register
    """
    form = OrganizationForm()
    if request.method == "POST":
        form = OrganizationForm(request.POST)
        if form.is_valid():
            post = form.save()
            # Check if commands field is specified
            if post.commands != '':
                # Convert comments field (string in yaml-format) to
                # json-editor friendly string
                post.commands = convert_dict_array(yaml.safe_load(post.commands))
            post.save()
            # Redirect to the main form page
            return HttpResponseRedirect(f"/{post.id}")
    return render(request, 'register.html', {'form': form})

def send_email(uuid, orgname, addresses):
    """
    Send email to specified addresses

    uuid: string with organization ID
    addresses: list of email addresses
    """
    date_time_now = str(datetime.now())[:-7]
    body = f"The webform https://data.solidex.by/{uuid}/ was \
updated at {date_time_now}."
    send_mail(
        f"{orgname} webform was updated",
        body,
        "webform@solidex.by",
        addresses,
        fail_silently=False)

def home(request, orgid):
    """
    Generate main form page

    Path in URL: /<uuid:orgid>/
        orgid: unique id of the organization
    """
    org_object = get_object_or_404(OrganizationModel, pk=orgid)
    # Get comments in yamldata string to display them instead of
    # some labels in web-form
    names_formats_orig = yaml_comments(org_object.yamldata)
    substitutions, formats, unique_orig = (names_formats_orig[0],
                                           names_formats_orig[1],
                                           names_formats_orig[2])
    unique_yamldata = names_formats_orig[3]
    yform = yaml.safe_load(unique_yamldata)  # Convert yaml-data to python object
    # Convert python object to string in json format
    json_from_yaml = json.dumps(yform, sort_keys=False)
    # List of contacts
    addresses = org_object.email_addresses.split(", ")
    if request.method == "POST":
        after_edit = request.POST.get("after_edit")
        substitutions = request.POST.get("substitutions")
        formats = request.POST.get("formats")
        unique_orig = request.POST.get("unique_orig")
        yaml_no_comments = yaml.safe_dump(json.loads(after_edit), sort_keys=False)
        org_object.yamldata = set_comments_back(yaml_no_comments, [json.loads(substitutions),
                                                                   json.loads(formats),
                                                                   json.loads(unique_orig)])
        org_object.save()
        send_email(orgid, org_object.company, addresses)
    return render(request, 'home.html', {'org_object': org_object,
                                         'orgid': orgid,
                                         'emails': addresses,
                                         'json_from_yaml': json_from_yaml,
                                         'substitutions': substitutions,
                                         'formats': formats,
                                         'unique_orig': unique_orig,
                                         })

def success(request, orgid):
    """
    Generate the page to informate customer that the data was sent successfully

    Path in URL: /<uuid:orgid>/success/
        orgid: unique id of the organization
    """
    org_object = get_object_or_404(OrganizationModel, pk=orgid)
    return render(request, 'success.html', {'org_object': org_object,
                                            'orgid': orgid, 
                                           })

def default(request):
    """
    Generate default page

    Path in URL: /
    """
    return render(request, 'default.html')


def files(request, orgid):
    """
    Generate page with possibility to upload, download and delete files

    Path in URL: /<uuid:orgid>/files/
        orgid: unique id of the organization
    """
    org_object = get_object_or_404(OrganizationModel, pk=orgid)
    # The page is accessible only if it should be used
    # That's why we check if the customer shouldn't provide any configs
    if org_object.num_conf == 0:
        raise Http404()
    docs = []
    # Get all the customer's files that they has already uploaded
    for doc in DocumentModel.objects.filter(organization__id=orgid):
        docs.append(doc)
    form = DocumentForm(request.POST or None)
    if 'upload_doc' in request.POST:
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.organization = org_object
            post.save()
            return HttpResponseRedirect(f"/{orgid}/files/")
    return render(request, 'files.html', {'org_object': org_object,
                                         'orgid': orgid,
                                         'comment': org_object.comment_conf,
                                         'docs': docs,
                                         'form': form,
                                         'current_uploaded_files': len(docs),
                                         'max_files': org_object.num_conf,
                                        })

def download_file(request, path):
    """
    Send user file if it exists

    Path in URL (also path parameter): /media/<uuid>/filename
        uuid: unique id of the organization
    """
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    # Check if file exists and if it's a file (not a directory)
    if os.path.exists(file_path) and os.path.isfile(file_path):
        with open(file_path, 'rb') as fh:
            # Send file and force browser to download it without displaying
            response = HttpResponse(fh.read(), content_type="application/force-download")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404()

def delete_file(request, orgid, fileid):
    """
    Delete file from server and database

    Path in URL: /<uuid:orgid>/files/<uuid:fileid>/
        orgid: unique id of the organization
        fileid: unique id of the file
    """
    org_object = get_object_or_404(OrganizationModel, pk=orgid)
    if request.method == 'POST':
        doc = DocumentModel.objects.get(pk=fileid)
        # Remove the file from the server
        os.remove(os.path.join(settings.MEDIA_ROOT, doc.document.name))
        doc.delete()  # Remove info about the file from the database
    return HttpResponseRedirect(f"/{orgid}/files/")

def commands(request, orgid):
    """
    Generate page with possibility to provide commands output

    Path in URL: /<uuid:orgid>/commands/
        orgid: unique id of the organization
    """
    org_object = get_object_or_404(OrganizationModel, pk=orgid)
    # The page is accessible only if it should be used
    # That's why we check if "commands" field is empty
    if org_object.commands == '':
        raise Http404()
    # Convert commands field in json-editor friendly schema
    commands_schema = commands_to_schema(json.loads(org_object.commands))
    if request.method == "POST":
        # Get filled data and save it
        filled_output = request.POST.get("filled_output")
        org_object.commands = filled_output
        org_object.save()
    return render(request, 'commands.html', {'org_object': org_object,
                                             'orgid': orgid,
                                             'commands_schema': commands_schema,
                                             })

def feedback(request, orgid):
    """
    Provide user with page to write a feedback

    Path in URL: /<uuid:orgid>/feedback/
        orgid: unique id of the organization
    """

    org_object = get_object_or_404(OrganizationModel, pk=orgid)
    feedback_obj = FeedbackModel.objects.filter(organization__id=orgid)
    if feedback_obj:
        instance = feedback_obj[0]
    else:
        instance = FeedbackModel()
    form = FeedbackForm(request.POST or None, instance=instance)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.organization = org_object
            post.save()
            return HttpResponseRedirect(f"/{orgid}/feedback/thanks")
    return render(request, 'feedback.html', {'org_object': org_object,
                                             'orgid': orgid,
                                             'form': form,
                                            })

def feedback_thanks(request, orgid):
    """
    Generate the page to informate customer that the feedback was sent successfully

    Path in URL: /<uuid:orgid>/feedback/thanks/
        orgid: unique id of the organization
    """
    org_object = get_object_or_404(OrganizationModel, pk=orgid)
    return render(request, 'feedback_thanks.html', {'org_object': org_object,
                                            'orgid': orgid, 
                                           })

def yaml_response(request, orgid):
    """
    Send yamldata field in plain yaml text

    Path in URL: /<uuid:orgid>/yamldata.yml
        orgid: unique id of the organization
    """
    org_object = get_object_or_404(OrganizationModel, pk=orgid)
    response = HttpResponse(org_object.yamldata, content_type="text/yaml")
    return response

def commands_response(request, orgid):
    """
    Send commands field in json format

main/templates/commands.html
{% extends 'base.html' %}

{% block title %} {{ org_object.company }} {% endblock %}

{% block orgname %}
  <a class="navbar-brand" href="{% url 'main:home' orgid %}">
  {{ org_object.company }}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'main:home' orgid %}">Home</a>
      {% if org_object.num_conf != 0 %}
        <a class="nav-item nav-link" href="{% url 'main:files' orgid %}">Files</a>
      {% endif %}
     <a class="nav-item nav-link active" href="{% url 'main:commands' orgid %}">Commands<span class="sr-only">(current)</span></a>
     <a class="nav-item nav-link" href="{% url 'main:feedback' orgid %}">Feedback</a>
    </div>
  </div>  
{% endblock %}

{% block content %}
  <style>
    .card.card-body.mb-3.bg-light {
      border: 0px dotted rgba(0,0,0,.125);
      background-color: white !important;
      margin-bottom: 0px !important;
     }

    .je-switcher{
       display: none;
       visibility: hidden;
       position: absolute;
       top: 0;
       bottom: 0;
     }

    label.h3 {
      display: inline-block;
      margin-bottom: 0rem;
    }

    h3.card-title.je-object__title {
      margin-bottom: 0;
    }

  </style>

  <div class='columns'>
     <div class='column col-md-12' id='editor_holder'></div>
  </div>
  <div class='columns'>
    <div class='column col-md-12 mt-0'>
      <button id='submit' class='btn btn-success ml-5 mb-4'>Отправить</button>
    </div>
  </div>
  
  <script type="text/javascript">
    JSONEditor.defaults.theme = 'bootstrap4';
    JSONEditor.defaults.iconlib = 'fontawesome5';
    JSONEditor.defaults.options["disable_edit_json"] = 1;
    JSONEditor.defaults.options["disable_collapse"] = 1;
    JSONEditor.defaults.options["disable_properties"] = 1;

    org_schema = JSON.stringify({{ commands_schema|safe }}).replace(/\n/g, "\\n").replace(/\r/g, "\\r").replace(/\t/g, "\\t")
    var editor = new JSONEditor(document.getElementById('editor_holder'),{
        // Enable fetching schemas via ajax
        ajax: true,
        
        // The schema for the editor
	schema: JSON.parse(org_schema),
        
        // Seed the form with a starting value
      });
    
    document.getElementById('submit').addEventListener('click',function() {
      $.ajax({
          url: "{% url 'main:commands' orgid %}",
          type: "POST",
          dataType: "json",
          xhrFields: { responseType: "document" },
          data: {
            url: "{% url 'main:commands' orgid %}",
            csrfmiddlewaretoken: '{{ csrf_token }}',
            "filled_output": JSON.stringify(editor.getValue())
          },
          success : function(json) {
            window.location = "{% url 'main:success' orgid %}"
          },
          error : function(xhr,errmsg,err) {
            window.location = "{% url 'main:success' orgid %}"
          }
      })
    });

    $(document).ready(function (){
	$("label").filter(function() {
            return $(this).text() == "Commands";
	}).replaceWith('<h5 class="mt-2" style="margin-bottom: 0px;">Введите указанные комманды в CLI соответствующих устройств. Скопируйте вывод комманд в соответствующие текстовые поля</h5>');

	$("textarea").attr("rows", "10");
    });
  </script>
{% endblock %}

main/templates/default.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron text-center">
    <h1 class="display-6">Портал сбора исходных данных</h1>
    <p class="lead">Для получения доступа к порталу используйте ссылку, содержащую уникальный идентификатор Вашей организации</p>
    <hr class="my-4">
    <p>В случае утраты идентификатора обратитесь по адресу
    	<a class="stretched-link" href="mailto:support@solidex.by" role="button">support@solidex.by</a>
    </p>
  </div>
{% endblock %}

main/templates/feedback.html
{% extends 'base.html' %}

{% block title %} {{ org_object.company }} {% endblock %}

{% block orgname %}
  <a class="navbar-brand" href="{% url 'main:home' orgid %}">
  {{ org_object.company }}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'main:home' orgid %}">Home</a>
      {% if org_object.num_conf != 0 %}
        <a class="nav-item nav-link" href="{% url 'main:files' orgid %}">Files</a>
      {% endif %}
      {% if org_object.commands != '' %}
        <a class="nav-item nav-link" href="{% url 'main:commands' orgid %}">Commands</a>
      {% endif %}
      <a class="nav-item nav-link active" href="{% url 'main:feedback' orgid %}">Feedback<span class="sr-only">(current)</span></a>
    </div>
  </div>
{% endblock %}

{% block content %}
  <h4 class="text-dark mb-4">Для улучшения качества портала, пожалуйста, ответьте на следующие вопросы</h4>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h6 class="form-text mb-2">Был ли портал удобен в использовании при предоставлении исходных данных?</h6>
    <div class="col-my-4 mb-4"> {{ form.is_user_friendly }}</div>
    <h6 class="form-text mb-2">Что бы Вы посоветовали улучшить в функционале портала?</h6>
    <div class="form-textarea mb-4"> {{ form.how_to_make_it_better }}</div>
    <button type="submit" name="create_form" class="btn btn-success mt-2 mb-4">
      Отправить
    </button>
  </form>
{% endblock %}

main/templates/feedback_thanks.html
{% extends 'base.html' %}

{% block title %} {{ org_object.company }} {% endblock %}

{% block orgname %}
  <a class="navbar-brand" href="{% url 'main:home' orgid %}">
  {{ org_object.company }}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-contr
ols="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'main:home' orgid %}">Home</a>
      {% if org_object.num_conf != 0 %}
        <a class="nav-item nav-link" href="{% url 'main:files' orgid %}">Files</a>
      {% endif %}
      {% if org_object.commands != '' %}
        <a class="nav-item nav-link" href="{% url 'main:commands' orgid %}">Commands</a>
      {% endif %}
      <a class="nav-item nav-link" href="{% url 'main:feedback' orgid %}">Feedback</a>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="jumbotron text-center">
    <h1 class="display-4 text-dark mb-3">Спасибо за Ваш отзыв!</h1>
    <a class="btn btn-secondary mt-4" href="{% url 'main:home' orgid %}" role="button">
       Вернуться к основной форме
    </a>
  </div>
{% endblock %}

main/templates/files.html
{% extends 'base.html' %}

{% block title %} {{ org_object.company }} {% endblock %}

{% block orgname %}
  <a class="navbar-brand" href="{% url 'main:home' orgid %}">
  {{ org_object.company }}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'main:home' orgid %}">Home</a>
      <a class="nav-item nav-link active" href="{% url 'main:files' orgid %}">Files<span class="sr-only">(current)</span></a>
      {% if org_object.commands != '' %}
        <a class="nav-item nav-link" href="{% url 'main:commands' orgid %}">Commands</a>
      {% endif %}
      <a class="nav-item nav-link" href="{% url 'main:feedback' orgid %}">Feedback</a>
    </div>
  </div>  
{% endblock %}


{% block content %}
  <h4 class="mb-4">{{ comment }}</h4>
  {% if docs %}
    <table class="table table-hover">
      <thead class="thead-light">
        <tr>
	  <th>Имя файла</th>
	  <th>Описание</th>
	  <th>Скачать</th>
	  <th>Удалить</th>
	</tr>
      </thead>
      <tbody>
	{% for doc in docs %}
	  <tr>
	    <td>
	      {{ doc.document.name | slice:"37:" }}
	    </td>
	    <td>
	      {{ doc.description  }}
	    </td>
	    <td>
	      <a href="{{ doc.document.url }}" class="btn btn-secondary" role="button">
	  	Скачать
	      </a>
	    </td>
	    <td>
	    	<form method="POST" action="{% url 'main:delete_file' orgid doc.id %}">
	    	  {% csrf_token %}
	    	  <button type="submit" class="btn btn-danger">Удалить</button>
	    	</form>
	    </td>
	  </tr>
       {% endfor %}
     </tbody>
   </table>
   {% endif %}

   {% if current_uploaded_files < max_files %}
     <form method="post" enctype="multipart/form-data">
       {% csrf_token %}
       <div class="form-group row ml-0">
     	 <div class="col-4 mr-2">
           <div class="form-text">Описание</div>
           <div class="input-sm"> {{ form.description }}</div>
         </div>
         <div class="col-xs-2">
           <div class="form-text">Файл</div>
	       <div type="file" class="mt-1"> {{ form.document }}</div>
	       <!--div class="custom-file">
	       <div type="file" class="custom-file-input mt-1" id="customFile"> {{ form.document }}</div>
            <label class="custom-file-label" for="customFile">Choose file</label>
           </div-->
	     </div>
       </div>
       <button type="submit" name="upload_doc" class="btn btn-success mt-0 ml-3 mb-4">
           Загрузить
       </button>
     </form>
    {% else %}
    	<p>Количество загруженных файлов достигнуто требуемого значения. Для загрузки новой версии существующего файла удалите исходный файл, затем загрузите его изменённую версию.
    {% endif %}
{% endblock %}

main/templates/register.html
{% extends 'base.html' %}
{% block title %} Register {% endblock %}

{% block content %}
  <form method="post"  enctype="multipart/form-data">
      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <p class="text-danger mt-2">{{ error }} </p>
          {% endfor %}
        {% endfor %}
      {% endif %}
      {% csrf_token %}
       <h6 class="form-text mb-2">Название компании:</h6>
       <div class="col-my-4 mb-4"> {{ form.company }}</div>
       <h6 class="form-text mb-2">Содержимое YAML файла:</h6>
       <div class="form-textarea mb-4"> {{ form.yamldata }}</div>
       <h6 class="form-text mb-2">Почтовые адреса работников</h6>
       <div class="col-my-4 mb-4"> {{ form.email_addresses }} </div>
       <div class="form-group row">
	       <div class="col-sm-6">
       	   <h6 class="form-text mb-2">Количество запрашиваемых конфигурационных файлов (default = 0, max = 10):</h6>
	       </div>
	       <div class="col-sm-2">
           <div class="form-textarea mb-4"> {{ form.num_conf }}</div>
	       </div>
       </div>
       <h6 class="form-text mb-2">К каким устройствам запрашиваются файлы (опишите в свободной форме):</h6>
       <div class="form-textarea mb-4"> {{ form.comment_conf }}</div>
       <h6 class="form-text mb-2">Команды, которые заказчик должен ввести в CLI каждого из устройств, чтобы потом предоставить их вывод:</h6>
       <div class="form-textarea mb-4"> {{ form.commands }}</div>
       <button type="submit" name="create_form" class="btn btn-success mt-2 mb-4">
            Отправить
       </button>
    </form>
{% endblock %}

main/templates/success.html
{% extends 'base.html' %}

{% block title %} {{ org_object.company }} {% endblock %}

{% block orgname %}
  <a class="navbar-brand" href="{% url 'main:home' orgid %}">
  {{ org_object.company }}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'main:home' orgid %}">Home</a>
      {% if org_object.num_conf != 0 %}
        <a class="nav-item nav-link" href="{% url 'main:files' orgid %}">Files</a>
      {% endif %}
      {% if org_object.commands != '' %}
        <a class="nav-item nav-link" href="{% url 'main:commands' orgid %}">Commands</a>
      {% endif %}
      <a class="nav-item nav-link" href="{% url 'main:feedback' orgid %}">Feedback</a>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="jumbotron text-center">
    <h1 class="display-5 text-dark mb-3">Ваши данные отправлены. Спасибо!</h1>
    <p class="lead mb-3">Для улучшения качества портала, пожалуйста, заполните <a class="stretched-link" href="{% url 'main:feedback' orgid %}" role="button">форму обратной связи</a></p>
    <hr>
    <a class="btn btn-secondary" href="{% url 'main:home' orgid %}" role="button">Редактировать данные</a>
  </div>
{% endblock %}